name: Release to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Set Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - name: Install Client-side Dependencies
        uses: borales/actions-yarn@v4
        with:
          cmd: deploy-production
      - name: AWS Deploy Push
        run: |
          aws deploy push \
          --application-name login-client \
          --description "This is a revision of cheddar login client" \
          --ignore-hidden-files \
          --s3-location s3://chdr-deploy/login-client/login-client-${{github.run_number}}.zip \
          --source .
      - name: AWS Create Deployment
        run: |
          aws deploy create-deployment \
           --application-name login-client \
           --deployment-group-name chdr-login-client-dg \
           --file-exists-behavior OVERWRITE \
           --s3-location bucket=chdr-deploy,key=login-client/login-client-${{github.run_number}}.zip,bundleType=zip